name = "Salinger"
license = "MIT"
licenselink = "https://github.com/jacksalici/salinger/blob/master/LICENSE"
description = "An extremely minimal hugo theme."
homepage = "jacksalici.com/salinger-hugo-theme"
tags = ["simple", "minimal", "clean", "fast", "blog", "portfolio", "responsive", "dark mode", "recursion", "section"]
features = ["fast", "blog", "sorting", "dark mode", "categories"]
min_version = "0.41.0"

[author]
  name = "Jack Salici"
  homepage = "jacksalici.com"



